/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WierszeIndexRouteImport } from './routes/wiersze/index'
import { Route as WierszeSlugRouteImport } from './routes/wiersze/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WierszeIndexRoute = WierszeIndexRouteImport.update({
  id: '/wiersze/',
  path: '/wiersze/',
  getParentRoute: () => rootRouteImport,
} as any)
const WierszeSlugRoute = WierszeSlugRouteImport.update({
  id: '/wiersze/$slug',
  path: '/wiersze/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/wiersze/$slug': typeof WierszeSlugRoute
  '/wiersze/': typeof WierszeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/wiersze/$slug': typeof WierszeSlugRoute
  '/wiersze': typeof WierszeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/wiersze/$slug': typeof WierszeSlugRoute
  '/wiersze/': typeof WierszeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/wiersze/$slug' | '/wiersze/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/wiersze/$slug' | '/wiersze'
  id: '__root__' | '/' | '/wiersze/$slug' | '/wiersze/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WierszeSlugRoute: typeof WierszeSlugRoute
  WierszeIndexRoute: typeof WierszeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wiersze/': {
      id: '/wiersze/'
      path: '/wiersze'
      fullPath: '/wiersze/'
      preLoaderRoute: typeof WierszeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wiersze/$slug': {
      id: '/wiersze/$slug'
      path: '/wiersze/$slug'
      fullPath: '/wiersze/$slug'
      preLoaderRoute: typeof WierszeSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WierszeSlugRoute: WierszeSlugRoute,
  WierszeIndexRoute: WierszeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
